### ISSUE TITLE
Better input TSV validation

### ISSUE THREAD

**Issue by nvictus** [mirnylab/cooler#209]
Consolidating multiple issues here:

- [ ] blacklist BED file with one entry #196
- [ ] bg2 file with a header #128
- [ ] malformed pairs file #135
- [ ] spaces instead of tabs in chromsizes file #124

**Comment by ShigrafS** [comment]
Hi @nvictus 
I have fixed the error cryptic error message issue (142). 
I would like to contribute to the repository.
