### ISSUE TITLE
Balancing enhancements

### ISSUE THREAD

**Issue by nvictus** [mirnylab/cooler#210]
Consolidating multiple issues:

- [ ] store median and MAD coverage in weight attrs #164
- [ ] add relative tolerance #131 
- [ ] add safety margin #83 
- [ ] alternative rescaling of cis-only weights #126
- [ ] add cis/total-based filtering #134
